const sampleData = {
  users: [
    {
      name: "John",
      email: "admin@example.com",
      password: "123456",
      role: "admin",
    },
    {
      name: "Jane",
      email: "user@example.com",
      password: "123456",
      role: "user",
    },
  ],
  products: [
    {
      name: "Running and Tennis Set | White",
      slug: "running-and-tennis-set-white",
      category: "Women's Sportswear",
      description: "Women’s Athletic Performance Set",
      images: [
        "/images/sample-products/p1-1.jpg",
        "/images/sample-products/p1-2.jpg",
      ],
      price: 39.99,
      brand: "Galvis",
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: "/images/banner-1.jpg",
    },
    {
      name: "Padel Set (Top & Skirt) | Navy Blue",
      slug: "padel-set-(Top-and-Skirt)-navy-blue",
      category: "Women's Sportswear",
      description: "Women’s Performance Court Outfit",
      images: ["/images/sample-products/p2.jpg"],
      price: 39.99,
      brand: "Galvis",
      rating: 4.6,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
      banner: "/images/banner-2.jpg",
    },
    {
      name: "Tennis & Padel Dress – White",
      slug: "tennis-&-Padel-dress-white",
      category: "Women's Sportswear",
      description: "Athletic Layer",
      images: ["/images/sample-products/p12.jpg"],
      price: 49.95,
      brand: "Galvis",
      rating: 4.1,
      numReviews: 16,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Cropped Zip Jacket - Sage Green",
      slug: "cropped-zip-jaket-sage-green",
      category: "Women's Sportswear",
      description: "Athletic Layer",
      images: ["/images/sample-products/p9.jpg"],
      price: 29.99,
      brand: "Galvis",
      rating: 4.4,
      numReviews: 6,
      stock: 7,
      isFeatured: false,
      banner: null,
    },
  ],
};

export default sampleData;
