const sampleData = {
  users: [
    {
      name: "John",
      email: "admin@example.com",
      password: "123456",
      role: "admin",
    },
    {
      name: "Jane",
      email: "user@example.com",
      password: "123456",
      role: "user",
    },
  ],
  products: [
    {
      name: "Running and Tennis Set | White",
      slug: "running-and-tennis-set-white",
      category: "Women's Sportswear",
      description: "Women’s Athletic Performance Set",
      images: [
        "/images/sample-products/p1-1.jpg",
        "/images/sample-products/p1-2.jpg",
      ],
      price: 39.99,
      brand: "Galvis",
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: "/images/banner-1.jpg",
    },
    {
      name: "Padel Set (Top & Skirt) | Navy Blue",
      slug: "padel-set-(Top & Skirt)-navy-blue",
      category: "Women's Sportswear",
      description: "Women’s Performance Court Outfit",
      images: ["/images/sample-products/p2.jpg"],
      price: 39.99,
      brand: "Galvis",
      rating: 4.6,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
      banner: "/images/banner-2.jpg",
    },
    {
      name: "High Support Sports Bra ",
      slug: "high-support-sports-bra ",
      category: "Women's Sportswear",
      description: "Performance Gym Bra",
      images: ["/images/sample-products/p3.jpg"],
      price: 14.99,
      brand: "Galvis",
      rating: 4.1,
      numReviews: 14,
      stock: 2,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Medium Support Sports Bra",
      slug: "medium-support-sports-bra",
      category: "Women's Sportswear",
      description: " Performance Gym Bra",
      images: ["/images/sample-products/p4.jpg"],
      price: 12.99,
      brand: "Galvis",
      rating: 4.3,
      numReviews: 7,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Medium Support Sports Bra",
      slug: "medium-support-sports-bra-green",
      category: "Women's Sportswear",
      description: "Performance Gym Bra",
      images: ["/images/sample-products/p5.jpg"],
      price: 19.99,
      brand: "Galvis",
      rating: 4.5,
      numReviews: 12,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: "High Impact Sports Bra",
      slug: "high-impact-sports-bra",
      category: "Women's Sportswear",
      description: "Maximum Support Gym Bra",
      images: ["/images/sample-products/p6.jpg"],
      price: 11.99,
      brand: "Galvis",
      rating: 3.9,
      numReviews: 4,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Running and Tennis Set | Brown",
      slug: "running-and-tennis-set-brown",
      category: "Women's Sportswear",
      description: "Sculpting Gym Set",
      images: [
        "/images/sample-products/p7-1.jpg",
        "/images/sample-products/p7-2.jpg",
      ],
      price: 59.99,
      brand: "Galvis",
      rating: 4.2,
      numReviews: 5,
      stock: 12,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Seamless Training Set",
      slug: "seamless-training-set",
      category: "Women's Sportswear",
      description: "Sculpting Gym Set",
      images: [
        "/images/sample-products/p8-1.jpg",
        "/images/sample-products/p8-2.jpg",
      ],
      price: 44.99,
      brand: "Galvis",
      rating: 4.7,
      numReviews: 3,
      stock: 23,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Cropped Zip Jacket - Sage Green",
      slug: "cropped-zip-jaket-sage-green",
      category: "Women's Sportswear",
      description: "Athletic Layer",
      images: ["/images/sample-products/p9.jpg"],
      price: 29.99,
      brand: "Galvis",
      rating: 4.4,
      numReviews: 6,
      stock: 7,
      isFeatured: false,
      banner: null,
    },
  ],
};

export default sampleData;
